package main

import (
	"math/rand"
)

// RandURL generates a random url from the given list
func RandCategory() string {
	categories := []string{
		"Abortion",
		"Adult/Mature Content",
		"Alcohol",
		"Alternative Spirituality/Belief",
		"Art/Culture",
		"Auctions",
		"Audio/Video Clips",
		"Brokerage/Trading",
		"Business/Economy",
		"Charitable/Non-Profit",
		"Chat (IM)/SMS",
		"Child Pornography",
		"Cloud Infrastructure",
		"Compromised Sites",
		"Computer/Information Security",
		"Content Delivery Networks",
		"Controlled Substances",
		"Cryptocurrency",
		"Dynamic DNS Host",
		"E-Card/Invitations",
		"Education",
		"Email",
		"Email Marketing",
		"Entertainment",
		"File Storage/Sharing",
		"Finance",
		"For Kids",
		"Gambling",
		"Games",
		"Gore/Extreme",
		"Government/Legal",
		"Hacking",
		"Health",
		"Humor/Jokes",
		"Informational",
		"Internet Connected Devices",
		"Internet Telephony",
		"Intimate Apparel/Swimsuit",
		"Job Search/Careers",
		"Malicious Outbound Data/Botnets",
		"Malicious Sources/Malnets",
		"Marijuana",
		"Media Sharing",
		"Military",
		"Mixed Content/Potentially Adult",
		"News",
		"Newsgroups/Forums",
		"Nudity",
		"Office/Business Applications",
		"Online Meetings",
		"Peer-to-Peer (P2P)",
		"Personal Sites",
		"Personals/Dating",
		"Phishing",
		"Piracy/Copyright Concerns",
		"Placeholders",
		"Political/Social Advocacy",
		"Pornography",
		"Potentially Unwanted Software",
		"Proxy Avoidance",
		"Radio/Audio Streams",
		"Real Estate",
		"Reference",
		"Religion",
		"Remote Access",
		"Restaurants/Food",
		"Scam/Questionable Legality",
		"Search Engines/Portals",
		"Sex Education",
		"Sexual Expression",
		"Shopping",
		"Social Networking",
		"Society/Daily Living",
		"Software Downloads",
		"Spam",
		"Sports/Recreation",
		"Suspicious",
		"Technology/Internet",
		"Tobacco",
		"Translation",
		"Travel",
		"TV/Video Streams",
		"Uncategorized",
		"URL Shorteners",
		"Vehicles",
		"Violence/Intolerance",
		"Weapons",
		"Web Ads/Analytics",
		"Web Hosting",
		"Web Infrastructure",
	}
	return categories[rand.Intn(len(categories))]
}
